"""Storage abstraction.

Documents are never served from a public bucket. Files are stored under an
opaque key and accessed only through short-lived signed URLs generated by the
API after an authorization check.

Two backends are provided:

* ``LocalStorage`` — filesystem storage with HMAC-signed, expiring URLs.
* ``S3Storage`` — interface-compatible stub for private S3-compatible buckets.

The ``s3`` backend raises until configured, so a half-configured production
deployment fails loudly instead of silently storing data insecurely.
"""

from __future__ import annotations

import hashlib
import hmac
import io
import os
import re
import time
from abc import ABC, abstractmethod
from pathlib import Path
from typing import BinaryIO
from urllib.parse import urlencode

from app.core.config import settings
from app.core.errors import AppError


class StorageError(AppError):
    code = "STORAGE_ERROR"
    status_code = 500


class StorageBackend(ABC):
    """Interface every storage provider must implement."""

    @abstractmethod
    async def put(self, key: str, data: bytes, content_type: str) -> None: ...

    @abstractmethod
    async def get(self, key: str) -> bytes: ...

    @abstractmethod
    async def delete(self, key: str) -> None: ...

    @abstractmethod
    def signed_url(
        self,
        key: str,
        ttl_seconds: int | None = None,
        *,
        disposition: str = "inline",
        content_type: str = "application/octet-stream",
        filename: str | None = None,
    ) -> str: ...

    @abstractmethod
    def verify_signed_url(
        self,
        key: str,
        expires: int,
        signature: str,
        *,
        disposition: str = "inline",
        content_type: str = "application/octet-stream",
    ) -> bool: ...


def _sign(key: str, expires: int, disposition: str, content_type: str) -> str:
    msg = f"{key}:{expires}:{disposition}:{content_type}".encode()
    return hmac.new(
        settings.SECRET_KEY.encode(), msg, hashlib.sha256
    ).hexdigest()


def sanitize_filename(name: str) -> str:
    """Return a header-safe filename (no quotes/CR/LF/path separators)."""
    base = os.path.basename(name or "document")
    cleaned = re.sub(r'[^A-Za-z0-9._\- ]+', "_", base).strip().strip(".")
    return cleaned[:200] or "document"


def content_disposition(disposition: str, filename: str) -> str:
    """Build a safe Content-Disposition value.

    ``inline`` lets the browser preview the file (used for in-app preview);
    ``attachment`` forces a download with the original filename.
    """
    kind = "inline" if disposition == "inline" else "attachment"
    safe = sanitize_filename(filename)
    # RFC 5987 form keeps non-ASCII names intact; the plain form is a fallback.
    from urllib.parse import quote

    return f"{kind}; filename=\"{safe}\"; filename*=UTF-8''{quote(safe)}"


class LocalStorage(StorageBackend):
    def __init__(self, root: str | None = None) -> None:
        self.root = Path(root or settings.STORAGE_LOCAL_ROOT).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        # Prevent path traversal — resolved path must stay under root.
        target = (self.root / key).resolve()
        if not str(target).startswith(str(self.root) + os.sep) and target != self.root:
            raise StorageError("Invalid storage key.")
        return target

    async def put(self, key: str, data: bytes, content_type: str) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    async def get(self, key: str) -> bytes:
        path = self._path(key)
        if not path.exists():
            raise StorageError("Document file is missing from storage.")
        return path.read_bytes()

    async def delete(self, key: str) -> None:
        path = self._path(key)
        if path.exists():
            path.unlink()

    def signed_url(
        self,
        key: str,
        ttl_seconds: int | None = None,
        *,
        disposition: str = "inline",
        content_type: str = "application/octet-stream",
        filename: str | None = None,
    ) -> str:
        expires = int(time.time()) + (ttl_seconds or settings.SIGNED_URL_TTL_SECONDS)
        signature = _sign(key, expires, disposition, content_type)
        params = {
            "key": key,
            "expires": expires,
            "signature": signature,
            "disposition": disposition,
            "content_type": content_type,
        }
        if filename:
            params["filename"] = filename
        return f"/api/v1/documents/file?{urlencode(params)}"

    def verify_signed_url(
        self,
        key: str,
        expires: int,
        signature: str,
        *,
        disposition: str = "inline",
        content_type: str = "application/octet-stream",
    ) -> bool:
        if expires < int(time.time()):
            return False
        return hmac.compare_digest(_sign(key, expires, disposition, content_type), signature)


class S3Storage(StorageBackend):
    """Private S3-compatible storage.

    A real implementation should use ``aioboto3``/``boto3`` with presigned
    URLs and server-side encryption. Until configured this backend refuses to
    operate rather than falling back to something insecure.
    """

    def __init__(self) -> None:
        if not settings.STORAGE_S3_BUCKET:
            raise StorageError(
                "S3 storage selected but STORAGE_S3_BUCKET is not configured."
            )
        self.bucket = settings.STORAGE_S3_BUCKET

    async def put(self, key: str, data: bytes, content_type: str) -> None:
        raise StorageError("S3 backend is not implemented in this build.")

    async def get(self, key: str) -> bytes:
        raise StorageError("S3 backend is not implemented in this build.")

    async def delete(self, key: str) -> None:
        raise StorageError("S3 backend is not implemented in this build.")

    def signed_url(
        self,
        key: str,
        ttl_seconds: int | None = None,
        *,
        disposition: str = "inline",
        content_type: str = "application/octet-stream",
        filename: str | None = None,
    ) -> str:
        raise StorageError("S3 backend is not implemented in this build.")

    def verify_signed_url(
        self,
        key: str,
        expires: int,
        signature: str,
        *,
        disposition: str = "inline",
        content_type: str = "application/octet-stream",
    ) -> bool:
        return False


_storage: StorageBackend | None = None


def get_storage() -> StorageBackend:
    global _storage
    if _storage is None:
        if settings.STORAGE_BACKEND == "s3":
            _storage = S3Storage()
        else:
            _storage = LocalStorage()
    return _storage


def build_storage_key(family_id: str, document_id: str, filename: str) -> str:
    """Opaque, non-guessable storage key preserving the extension only."""
    suffix = Path(filename).suffix.lower()[:10]
    safe_suffix = suffix if suffix.isalnum() or suffix.startswith(".") else ""
    return f"{family_id}/{document_id}{safe_suffix}"


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sniff_content_type(data: bytes, declared: str) -> str | None:
    """Detect the real content type from magic bytes.

    Returns the detected type or ``None`` if the bytes are not a supported
    file type. This prevents content-type spoofing of uploads.
    """
    if data.startswith(b"%PDF-"):
        return "application/pdf"
    if data.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        return "image/webp"
    if data.startswith(b"{\\rtf"):
        return "application/rtf"
    # OLE compound file (legacy .doc, and older .xls/.ppt).
    if data.startswith(b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"):
        return "application/msword"
    # DOCX/XLSX/PPTX are ZIP containers; only accept the Word document part.
    if data.startswith(b"PK\x03\x04"):
        import zipfile

        try:
            with zipfile.ZipFile(io.BytesIO(data)) as archive:
                names = set(archive.namelist())
        except Exception:  # noqa: BLE001
            return None
        if "word/document.xml" in names:
            return (
                "application/vnd.openxmlformats-officedocument."
                "wordprocessingml.document"
            )
        return None
    # Plain text: no magic bytes, so validate that it decodes and looks textual.
    if declared in {"text/plain"} or _looks_like_text(data):
        if _looks_like_text(data):
            return "text/plain"
    return None


def _looks_like_text(data: bytes) -> bool:
    sample = data[:4096]
    if not sample:
        return False
    if b"\x00" in sample:
        return False
    try:
        sample.decode("utf-8")
    except UnicodeDecodeError:
        return False
    # Require a reasonable proportion of printable characters.
    printable = sum(1 for b in sample if 32 <= b < 127 or b in (9, 10, 13))
    return printable / len(sample) > 0.9
